language: python
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
python:
  - 2.7
  - 3.4
  - pypy
install:
  - make
script:
  - make test
matrix:
  allow_failures:
    - python: pypy
    - python: 3.4
      env: "DJANGO_VERSION=1.4"
