language: python
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - make
script:
  - make test
matrix:
  allow_failures:
    - python: pypy
    - python: 3.2
      env: "DJANGO_VERSION=1.4"
    - python: 3.3
      env: "DJANGO_VERSION=1.4"
