language: python
# Don't build on 2.4 because 2.4 support is broken.
python:
  - 2.5
  - 2.6
  - 2.7
install: 
  - pip install mock --use-mirrors
  - pip install .
script:
  - python src/djangorecipe/tests.py
  
